services:
  postgres-1000car-multimarcas:
    image: postgres:17-alpine
    container_name: postgres-1000car-multimarcas
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_1000car_data:/var/lib/postgresql/data
      - ./1000car-multimarcas/create-table.sql:/docker-entrypoint-initdb.d/1-create-table.sql
      - ./1000car-multimarcas/copy-table.sql:/docker-entrypoint-initdb.d/2-copy-table.sql
      - ./1000car-multimarcas-campanha/csv:/csv
    networks:
      - abp-network
    
  server.app:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: server.app
    restart: always
    networks:
      - abp-network
    depends_on:
      - postgres-1000car-multimarcas
    env_file:
      - ./.env
    volumes:
      - ./server:/usr/src/abp
      - ./logs:/usr/src/app/logs
    command: sh -c "npx prisma generate && npm run dev"
    ports:
      - "3001:3000"

  public-app:
    build:
      context: ./public
      dockerfile: Dockerfile
    container_name: public-app
    restart: always
    networks:
      - abp-network
    env_file:
      - ./.env
    depends_on:
      - server.app
    environment:
      CHOKIDAR_USEPOLLING: "true" # Garante Hot Reload dentro do container
    volumes:
      - ./public:/usr/src/app       # Código local
      - /usr/src/app/node_modules   # Mantém dependências no container
    command: npm run dev -- --host
    ports:
      - "3002:5173"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports: 
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - abp-network
    depends_on:
      - postgres-1000car-multimarcas

volumes:
  postgres_1000car_data:
  pgadmin_data:

networks:
  abp-network:
    driver: bridge
