ALTER TABLE "Usuario"
ADD COLUMN "telefone" TEXT,
ADD COLUMN "role" TEXT NOT NULL DEFAULT 'USUARIO',
ADD COLUMN "ativo" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "ultimoLogin" TIMESTAMP(3),
ADD COLUMN "permissoes" JSONB;
